# Use Python 3.12 slim-buster base image
FROM python:3.12-slim

# Set environment variables for non-interactive execution
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the Streamlit application file
COPY streamlit_ui.py .

# Copy frontend requirements.txt from the root, install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run the Streamlit application
ENTRYPOINT ["streamlit", "run", "streamlit_ui.py", "--server.port=8501", "--server.address=0.0.0.0", "--logger.level=info"]
